// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvd5EHbWzSQCoYQY4ZhfdAsrSR_KogIFY',
    appId: '1:1028255303356:web:48fdedaaeaf80e93baf2b9',
    messagingSenderId: '1028255303356',
    projectId: 'jewelio',
    authDomain: 'jewelio.firebaseapp.com',
    storageBucket: 'jewelio.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz0F2pmxo4ii1r-6Krtev-kefRC5HPhPQ',
    appId: '1:1028255303356:android:8ecdb1b1053efdd5baf2b9',
    messagingSenderId: '1028255303356',
    projectId: 'jewelio',
    storageBucket: 'jewelio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmnHYXIU35-c_WRo9eM9jBWnnC4RrA-jc',
    appId: '1:1028255303356:ios:dc1b3c524a6801efbaf2b9',
    messagingSenderId: '1028255303356',
    projectId: 'jewelio',
    storageBucket: 'jewelio.firebasestorage.app',
    iosBundleId: 'com.example.jewelio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmnHYXIU35-c_WRo9eM9jBWnnC4RrA-jc',
    appId: '1:1028255303356:ios:dc1b3c524a6801efbaf2b9',
    messagingSenderId: '1028255303356',
    projectId: 'jewelio',
    storageBucket: 'jewelio.firebasestorage.app',
    iosBundleId: 'com.example.jewelio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvd5EHbWzSQCoYQY4ZhfdAsrSR_KogIFY',
    appId: '1:1028255303356:web:94a2f64fc54c3a10baf2b9',
    messagingSenderId: '1028255303356',
    projectId: 'jewelio',
    authDomain: 'jewelio.firebaseapp.com',
    storageBucket: 'jewelio.firebasestorage.app',
  );
}
